sudo: false
language: python - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python="2.7" sphinx
    - pip install --upgrade pip
    - pip install --user travis-sphinx
    - export PATH=$HOME/.local/bin:$PATH
    - pip install sphinx sphinx-autobuild
    - pip install --user sphinx_rtd_theme

script:
    - travis-sphinx build --nowarn
    
after_success:
    - travis-sphinx deploy
on:
    branch: master

before_deploy:
    - find * -type d | grep -v "\<doc\>" | xargs rm -r || true
    - mv doc/build/{.,}* . || true
    - rm -rf doc
    - rm README.md .travis.yml .git.ignore || true
    - touch .nojekyll
on:
    branch: dev

deploy:

-
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  repo: gcharang/KomodoDocs-Preview
  target-branch: master
  on:
    branch: dev
